language: perl

perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

install:
  - cpanm --quiet --notest --skip-satisfied Dist::Zilla Software::License::GPL_2::or_later
  - dzil authordeps --missing | cpanm --quiet --notest
  - dzil listdeps --missing | cpanm --quiet --notest

# full author tests only once, smoke tests everywhere else
script:
  - if test $TRAVIS_PERL_VERSION = '5.22'; then cpanm --quiet --notest --skip-satisfied Pod::Coverage::TrustPod && dzil test --keep; else dzil smoke; fi

# run coverage only once and on non-mongled, non-PodWeavered code or line numbers won't match
after_success:
  - test $TRAVIS_PERL_VERSION = '5.22' && cpanm --quiet --notest --skip-satisfied Devel::Cover Devel::Cover::Report::Codecov && cp .build/*/Makefile* . && cover -test -report codecov
